services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - public
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - public
      - internal
    depends_on:
      - cache

  cache:
    image: redis:7-alpine
    networks:
      - internal
    volumes:
      - redis_data:/data

volumes:
  redis_data:

networks:
  public:
  internal:
