# --- REDIS ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-redis
  namespace: taskflow-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskflow-redis
  template:
    metadata:
      labels:
        app: taskflow-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
---
# --- BACKEND ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-backend
  namespace: taskflow-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskflow-backend
  template:
    metadata:
      labels:
        app: taskflow-backend
    spec:
      containers:
      - name: backend
        image: miyxki/taskflow-backend:v1.0.3
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: taskflow-config
        - secretRef:
            name: taskflow-secrets
---
# --- FRONTEND ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-frontend
  namespace: taskflow-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskflow-frontend
  template:
    metadata:
      labels:
        app: taskflow-frontend
    spec:
      containers:
      - name: frontend
        image: miyxki/taskflow-frontend:v1.0.5
        ports:
        - containerPort: 80
