# --- SERVICE REDIS ---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: taskflow-staging
spec:
  type: ClusterIP
  selector:
    app: taskflow-redis
  ports:
    - port: 6379
---
# --- SERVICE BACKEND ---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: taskflow-staging
spec:
  type: NodePort
  selector:
    app: taskflow-backend
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30002
---
# --- SERVICE FRONTEND ---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: taskflow-staging
spec:
  type: NodePort
  selector:
    app: taskflow-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30082
