# --- SERVICE FRONTEND ---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: taskflow-production
spec:
  type: NodePort # Obligatoire pour le niveau socle du TP
  selector:
    app: taskflow-frontend # Doit être identique au label du deployment
  ports:
    - protocol: TCP
      port: 80         # Port exposé à l'intérieur du cluster
      targetPort: 80   # Port dans le container (Dockerfile EXPOSE 80)
      nodePort: 30080  # Port accessible sur l'IP de Minikube (entre 30000-32767)

---
# --- SERVICE BACKEND ---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: taskflow-production
spec:
  type: NodePort
  selector:
    app: taskflow-backend # Doit être identique au label du deployment
  ports:
    - protocol: TCP
      port: 3001       # Port exposé à l'intérieur du cluster
      targetPort: 3001 # Port dans le container (vu dans app.js)
      nodePort: 30001  # Port accessible sur l'IP de Minikube
